# Site settings

title: Trasnochando y Filosofando
author:
  name: Patricio Garrido
  email: garridopatricio514@gmail.com
description: "El mejor sitio con los mejores fragmentos y reflexiones filosóficas."

# Build settings
remote_theme: jekyll/minima
